export const WEATHER = {
    GET_WEATHER_BY_CITY:"GET_WEATHER_BY_CITY",
    DELETE_WEATHER_FROM_LIST:"DELETE_WEATHER_FROM_LIST",
    CHANGE_TO:"CHANGE_TO",
    CHANGE_TO_CELCIUS:"CHANGE_TO_CELCIUS",
    CHANGE_TO_FEHRENHEIGHT:"CHANGE_TO_FEHRENHEIGHT",
    CHANGE_TO_KELVIN:"CHANGE_TO_KELVIN",
}